/* INFO ************************************************************************
**                                                                            **
**                                  pycasso                                   **
**                                  =======                                   **
**                                                                            **
**    Cross-platform, hardware accelerated, constraint based GUI framework    **
**                       Version: 0.5.02.039 (20140911)                       **
**                                                                            **
**                         File: resources/shaders.h                          **
**                                                                            **
**  For more information about the project, visit <http://www.pycasso.org>.   **
**                       Copyright (C) 2014 Peter Varo                        **
**                                                                            **
**  This program is free software: you can redistribute it and/or modify it   **
**   under the terms of the GNU General Public License as published by the    **
**       Free Software Foundation, either version 3 of the License, or        **
**                    (at your option) any later version.                     **
**                                                                            **
**    This program is distributed in the hope that it will be useful, but     **
**         WITHOUT ANY WARRANTY; without even the implied warranty of         **
**            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.            **
**            See the GNU General Public License for more details.            **
**                                                                            **
**     You should have received a copy of the GNU General Public License      **
**     along with this program, most likely a file in the root directory,     **
**        called 'LICENSE'. If not, see <http://www.gnu.org/licenses>.        **
**                                                                            **
************************************************************************ INFO */

#ifndef _PYCASSO_RESOURCES_SHADERS_26875033728857023_
#define _PYCASSO_RESOURCES_SHADERS_26875033728857023_

enum
{
    MAIN_VS,
    QUAD_COLOR_VS,
    QUAD_TEXTURE_VS,
    SYS_GRID_VS,
    MAIN_FS,
    SHAPE_CIRCLE_FS,
    SHAPE_RECTANGLE_FS,
    SHAPE_ROUNDED_RECTANGLE_FS,
    FILL_SOLID_COLOR_FS,
    FILL_TEXTURE_FS,
    FILL_LINEAR_GRADIENT_FS,
    FILL_RADIAL_GRADIENT_FS,
    FILL_CONICAL_GRADIENT_FS
};

static const char *SHADER_SOURCES[] =
{
    [MAIN_VS] =
    "// INFO ////////////////////////////////////////////////////////////////////////\n"
    "//                                                                            //\n"
    "//                                  pycasso                                   //\n"
    "//                                  =======                                   //\n"
    "//                                                                            //\n"
    "//    Cross-platform, hardware accelerated, constraint based GUI framework    //\n"
    "//                       Version: 0.5.02.035 (20140911)                       //\n"
    "//                                                                            //\n"
    "//                        File: shaders/vertex/main.vs                        //\n"
    "//                                                                            //\n"
    "//  For more information about the project, visit <http://www.pycasso.org>.   //\n"
    "//                       Copyright (C) 2014 Peter Varo                        //\n"
    "//                                                                            //\n"
    "//  This program is free software: you can redistribute it and/or modify it   //\n"
    "//   under the terms of the GNU General Public License as published by the    //\n"
    "//       Free Software Foundation, either version 3 of the License, or        //\n"
    "//                    (at your option) any later version.                     //\n"
    "//                                                                            //\n"
    "//    This program is distributed in the hope that it will be useful, but     //\n"
    "//         WITHOUT ANY WARRANTY; without even the implied warranty of         //\n"
    "//            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.            //\n"
    "//            See the GNU General Public License for more details.            //\n"
    "//                                                                            //\n"
    "//     You should have received a copy of the GNU General Public License      //\n"
    "//     along with this program, most likely a file in the root directory,     //\n"
    "//        called 'LICENSE'. If not, see <http://www.gnu.org/licenses>.        //\n"
    "//                                                                            //\n"
    "//////////////////////////////////////////////////////////////////////// INFO //\n"
    "\n"
    "// OpenGL Shading Language Version 1.50\n"
    "#version 150 core\n"
    "\n"
    "void geometry(in vec2 coordinates, out vec4 position);\n"
    "\n"
    "// Output for fragment shader\n"
    "in  vec2 vertex_coordinates;\n"
    "out vec2 vertices;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 position;\n"
    "\n"
    "    geometry(vertex_coordinates, position);\n"
    "\n"
    "    gl_Position = position;\n"
    "    vertices = vertex_coordinates;\n"
    "}\n",

    [QUAD_COLOR_VS] =
    "// INFO ////////////////////////////////////////////////////////////////////////\n"
    "//                                                                            //\n"
    "//                                  pycasso                                   //\n"
    "//                                  =======                                   //\n"
    "//                                                                            //\n"
    "//    Cross-platform, hardware accelerated, constraint based GUI framework    //\n"
    "//                       Version: 0.5.02.035 (20140911)                       //\n"
    "//                                                                            //\n"
    "//                     File: shaders/vertex/quad_color.vs                     //\n"
    "//                                                                            //\n"
    "//  For more information about the project, visit <http://www.pycasso.org>.   //\n"
    "//                       Copyright (C) 2014 Peter Varo                        //\n"
    "//                                                                            //\n"
    "//  This program is free software: you can redistribute it and/or modify it   //\n"
    "//   under the terms of the GNU General Public License as published by the    //\n"
    "//       Free Software Foundation, either version 3 of the License, or        //\n"
    "//                    (at your option) any later version.                     //\n"
    "//                                                                            //\n"
    "//    This program is distributed in the hope that it will be useful, but     //\n"
    "//         WITHOUT ANY WARRANTY; without even the implied warranty of         //\n"
    "//            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.            //\n"
    "//            See the GNU General Public License for more details.            //\n"
    "//                                                                            //\n"
    "//     You should have received a copy of the GNU General Public License      //\n"
    "//     along with this program, most likely a file in the root directory,     //\n"
    "//        called 'LICENSE'. If not, see <http://www.gnu.org/licenses>.        //\n"
    "//                                                                            //\n"
    "//////////////////////////////////////////////////////////////////////// INFO //\n"
    "\n"
    "// OpenGL Shading Language Version 1.50\n"
    "#version 150 core\n"
    "\n"
    "// uniform GlobalMatrix\n"
    "// {\n"
    "//     mat4 projection_mat;\n"
    "// }\n"
    "\n"
    "uniform mat4 projection_mat;\n"
    "uniform mat4 view_mat;\n"
    "uniform mat4 model_mat;\n"
    "\n"
    "void geometry(in vec2 coordinates, out vec4 position)\n"
    "{\n"
    "    position = vec(coordinates, 0.f, 1.f);\n"
    "    // position = projection_mat * view_mat * model_mat * vec4(coordinates, 0.f, 1.f);\n"
    "}\n",

    [QUAD_TEXTURE_VS] =
    "// INFO ////////////////////////////////////////////////////////////////////////\n"
    "//                                                                            //\n"
    "//                                  pycasso                                   //\n"
    "//                                  =======                                   //\n"
    "//                                                                            //\n"
    "//    Cross-platform, hardware accelerated, constraint based GUI framework    //\n"
    "//                       Version: 0.5.02.035 (20140911)                       //\n"
    "//                                                                            //\n"
    "//                    File: shaders/vertex/quad_texture.vs                    //\n"
    "//                                                                            //\n"
    "//  For more information about the project, visit <http://www.pycasso.org>.   //\n"
    "//                       Copyright (C) 2014 Peter Varo                        //\n"
    "//                                                                            //\n"
    "//  This program is free software: you can redistribute it and/or modify it   //\n"
    "//   under the terms of the GNU General Public License as published by the    //\n"
    "//       Free Software Foundation, either version 3 of the License, or        //\n"
    "//                    (at your option) any later version.                     //\n"
    "//                                                                            //\n"
    "//    This program is distributed in the hope that it will be useful, but     //\n"
    "//         WITHOUT ANY WARRANTY; without even the implied warranty of         //\n"
    "//            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.            //\n"
    "//            See the GNU General Public License for more details.            //\n"
    "//                                                                            //\n"
    "//     You should have received a copy of the GNU General Public License      //\n"
    "//     along with this program, most likely a file in the root directory,     //\n"
    "//        called 'LICENSE'. If not, see <http://www.gnu.org/licenses>.        //\n"
    "//                                                                            //\n"
    "//////////////////////////////////////////////////////////////////////// INFO //\n"
    "\n"
    "// OpenGL Shading Language Version 1.50\n"
    "#version 150 core\n"
    "\n"
    "uniform mat4 projection_mat;\n"
    "uniform mat4 view_mat;\n"
    "uniform mat4 model_mat;\n"
    "\n"
    "// in vec2 texture_coordinates;\n"
    "\n"
    "void geometry(in vec2 coordinates, out vec4 position)\n"
    "{\n"
    "    position = projection_mat * view_mat * model_mat * vec4(coordinates, 0.f, 1.f);\n"
    "}\n"
    "\n"
    "// void texture(in vec2 coordinates, out vec2 textures)\n"
    "// {\n"
    "//     textures = coordinates;\n"
    "// }\n",

    [SYS_GRID_VS] =
    "// INFO ////////////////////////////////////////////////////////////////////////\n"
    "//                                                                            //\n"
    "//                                  pycasso                                   //\n"
    "//                                  =======                                   //\n"
    "//                                                                            //\n"
    "//    Cross-platform, hardware accelerated, constraint based GUI framework    //\n"
    "//                       Version: 0.5.02.035 (20140911)                       //\n"
    "//                                                                            //\n"
    "//                      File: shaders/vertex/sys_grid.vs                      //\n"
    "//                                                                            //\n"
    "//  For more information about the project, visit <http://www.pycasso.org>.   //\n"
    "//                       Copyright (C) 2014 Peter Varo                        //\n"
    "//                                                                            //\n"
    "//  This program is free software: you can redistribute it and/or modify it   //\n"
    "//   under the terms of the GNU General Public License as published by the    //\n"
    "//       Free Software Foundation, either version 3 of the License, or        //\n"
    "//                    (at your option) any later version.                     //\n"
    "//                                                                            //\n"
    "//    This program is distributed in the hope that it will be useful, but     //\n"
    "//         WITHOUT ANY WARRANTY; without even the implied warranty of         //\n"
    "//            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.            //\n"
    "//            See the GNU General Public License for more details.            //\n"
    "//                                                                            //\n"
    "//     You should have received a copy of the GNU General Public License      //\n"
    "//     along with this program, most likely a file in the root directory,     //\n"
    "//        called 'LICENSE'. If not, see <http://www.gnu.org/licenses>.        //\n"
    "//                                                                            //\n"
    "//////////////////////////////////////////////////////////////////////// INFO //\n"
    "\n"
    "// OpenGL Shading Language Version 1.50\n"
    "#version 150 core\n"
    "\n"
    "uniform mat4 projection_mat;\n"
    "uniform mat4 view_mat;\n"
    "\n"
    "void geometry(in vec2 coordinates, out vec4 position)\n"
    "{\n"
    "    position = projection_mat * view_mat * vec4(coordinates, 0.f, 1.f);\n"
    "}\n",

    [MAIN_FS] =
    "// INFO ////////////////////////////////////////////////////////////////////////\n"
    "//                                                                            //\n"
    "//                                  pycasso                                   //\n"
    "//                                  =======                                   //\n"
    "//                                                                            //\n"
    "//    Cross-platform, hardware accelerated, constraint based GUI framework    //\n"
    "//                       Version: 0.5.02.035 (20140911)                       //\n"
    "//                                                                            //\n"
    "//                       File: shaders/fragment/main.fs                       //\n"
    "//                                                                            //\n"
    "//  For more information about the project, visit <http://www.pycasso.org>.   //\n"
    "//                       Copyright (C) 2014 Peter Varo                        //\n"
    "//                                                                            //\n"
    "//  This program is free software: you can redistribute it and/or modify it   //\n"
    "//   under the terms of the GNU General Public License as published by the    //\n"
    "//       Free Software Foundation, either version 3 of the License, or        //\n"
    "//                    (at your option) any later version.                     //\n"
    "//                                                                            //\n"
    "//    This program is distributed in the hope that it will be useful, but     //\n"
    "//         WITHOUT ANY WARRANTY; without even the implied warranty of         //\n"
    "//            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.            //\n"
    "//            See the GNU General Public License for more details.            //\n"
    "//                                                                            //\n"
    "//     You should have received a copy of the GNU General Public License      //\n"
    "//     along with this program, most likely a file in the root directory,     //\n"
    "//        called 'LICENSE'. If not, see <http://www.gnu.org/licenses>.        //\n"
    "//                                                                            //\n"
    "//////////////////////////////////////////////////////////////////////// INFO //\n"
    "\n"
    "// OpenGL Shading Language Version 1.50\n"
    "#version 150 core\n"
    "\n"
    "void fill(in vec2 vertices, out vec4 color);\n"
    "void shape(in vec2 vertices, out float alpha);\n"
    "\n"
    "in  vec2 vertices;\n"
    "out vec4 fragment;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4  color;\n"
    "    float alpha;\n"
    "\n"
    "    fill(vertices, color);\n"
    "    shape(vertices, alpha);\n"
    "\n"
    "    fragment = vec4(color.rgb, color.a*alpha) ;\n"
    "}\n",

    [SHAPE_CIRCLE_FS] =
    "// INFO ////////////////////////////////////////////////////////////////////////\n"
    "//                                                                            //\n"
    "//                                  pycasso                                   //\n"
    "//                                  =======                                   //\n"
    "//                                                                            //\n"
    "//    Cross-platform, hardware accelerated, constraint based GUI framework    //\n"
    "//                       Version: 0.5.02.035 (20140911)                       //\n"
    "//                                                                            //\n"
    "//                   File: shaders/fragment/shape_circle.fs                   //\n"
    "//                                                                            //\n"
    "//  For more information about the project, visit <http://www.pycasso.org>.   //\n"
    "//                       Copyright (C) 2014 Peter Varo                        //\n"
    "//                                                                            //\n"
    "//  This program is free software: you can redistribute it and/or modify it   //\n"
    "//   under the terms of the GNU General Public License as published by the    //\n"
    "//       Free Software Foundation, either version 3 of the License, or        //\n"
    "//                    (at your option) any later version.                     //\n"
    "//                                                                            //\n"
    "//    This program is distributed in the hope that it will be useful, but     //\n"
    "//         WITHOUT ANY WARRANTY; without even the implied warranty of         //\n"
    "//            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.            //\n"
    "//            See the GNU General Public License for more details.            //\n"
    "//                                                                            //\n"
    "//     You should have received a copy of the GNU General Public License      //\n"
    "//     along with this program, most likely a file in the root directory,     //\n"
    "//        called 'LICENSE'. If not, see <http://www.gnu.org/licenses>.        //\n"
    "//                                                                            //\n"
    "//////////////////////////////////////////////////////////////////////// INFO //\n"
    "\n"
    "// OpenGL Shading Language Version 1.50\n"
    "#version 150 core\n"
    "\n"
    "void shape(in vec2 vertices, out float alpha)\n"
    "{\n"
    "    // Radius is constant, always .5f, so\n"
    "    // origo is constant too always .5f, .5f\n"
    "    alpha = 1.f - smoothstep(.4925f, .5f, distance(vec2(.5f), vertices.xy));\n"
    "}\n",

    [SHAPE_RECTANGLE_FS] =
    "// INFO ////////////////////////////////////////////////////////////////////////\n"
    "//                                                                            //\n"
    "//                                  pycasso                                   //\n"
    "//                                  =======                                   //\n"
    "//                                                                            //\n"
    "//    Cross-platform, hardware accelerated, constraint based GUI framework    //\n"
    "//                       Version: 0.5.02.035 (20140911)                       //\n"
    "//                                                                            //\n"
    "//                 File: shaders/fragment/shape_rectangle.fs                  //\n"
    "//                                                                            //\n"
    "//  For more information about the project, visit <http://www.pycasso.org>.   //\n"
    "//                       Copyright (C) 2014 Peter Varo                        //\n"
    "//                                                                            //\n"
    "//  This program is free software: you can redistribute it and/or modify it   //\n"
    "//   under the terms of the GNU General Public License as published by the    //\n"
    "//       Free Software Foundation, either version 3 of the License, or        //\n"
    "//                    (at your option) any later version.                     //\n"
    "//                                                                            //\n"
    "//    This program is distributed in the hope that it will be useful, but     //\n"
    "//         WITHOUT ANY WARRANTY; without even the implied warranty of         //\n"
    "//            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.            //\n"
    "//            See the GNU General Public License for more details.            //\n"
    "//                                                                            //\n"
    "//     You should have received a copy of the GNU General Public License      //\n"
    "//     along with this program, most likely a file in the root directory,     //\n"
    "//        called 'LICENSE'. If not, see <http://www.gnu.org/licenses>.        //\n"
    "//                                                                            //\n"
    "//////////////////////////////////////////////////////////////////////// INFO //\n"
    "\n"
    "#version 150 core\n"
    "\n"
    "void shape(in vec2 vertices, out float alpha)\n"
    "{\n"
    "    alpha = 1.f;\n"
    "}\n",

    [SHAPE_ROUNDED_RECTANGLE_FS] =
    "// INFO ////////////////////////////////////////////////////////////////////////\n"
    "//                                                                            //\n"
    "//                                  pycasso                                   //\n"
    "//                                  =======                                   //\n"
    "//                                                                            //\n"
    "//    Cross-platform, hardware accelerated, constraint based GUI framework    //\n"
    "//                       Version: 0.5.02.035 (20140911)                       //\n"
    "//                                                                            //\n"
    "//             File: shaders/fragment/shape_rounded_rectangle.fs              //\n"
    "//                                                                            //\n"
    "//  For more information about the project, visit <http://www.pycasso.org>.   //\n"
    "//                       Copyright (C) 2014 Peter Varo                        //\n"
    "//                                                                            //\n"
    "//  This program is free software: you can redistribute it and/or modify it   //\n"
    "//   under the terms of the GNU General Public License as published by the    //\n"
    "//       Free Software Foundation, either version 3 of the License, or        //\n"
    "//                    (at your option) any later version.                     //\n"
    "//                                                                            //\n"
    "//    This program is distributed in the hope that it will be useful, but     //\n"
    "//         WITHOUT ANY WARRANTY; without even the implied warranty of         //\n"
    "//            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.            //\n"
    "//            See the GNU General Public License for more details.            //\n"
    "//                                                                            //\n"
    "//     You should have received a copy of the GNU General Public License      //\n"
    "//     along with this program, most likely a file in the root directory,     //\n"
    "//        called 'LICENSE'. If not, see <http://www.gnu.org/licenses>.        //\n"
    "//                                                                            //\n"
    "//////////////////////////////////////////////////////////////////////// INFO //\n"
    "\n"
    "// OpenGL Shading Language Version 1.50\n"
    "#version 150 core\n"
    "\n"
    "uniform vec2  dimensions;\n"
    "uniform vec4  radiuses;\n"
    "\n"
    "/*  0-----1\n"
    "    |     |  -> radiuses\n"
    "    |     |\n"
    "    3-----2  */\n"
    "\n"
    "void shape(in vec2 vertices, out float alpha)\n"
    "{\n"
    "    // Top-left, Top-right, Bottom-right, Bottom-left\n"
    "    vec2  tl, tr, br, bl;\n"
    "\n"
    "    // Center of corner arcs\n"
    "    tl = vec2( radiuses[0],                 dimensions[1] - radiuses[0] );\n"
    "    tr = vec2( dimensions[0] - radiuses[1], dimensions[1] - radiuses[1] );\n"
    "    br = vec2( dimensions[0] - radiuses[2], radiuses[2]                 );\n"
    "    bl = vec2( radiuses[3],                 radiuses[3]                 );\n"
    "\n"
    "    // vec2 coord = clamp(vertices, tl);\n"
    "\n"
    "    // If Top-left\n"
    "    if (vertices.x < tl.x && vertices.y > tl.y)\n"
    "    {\n"
    "        alpha = 1.f - smoothstep(radiuses[0] - .0075f, radiuses[0], distance(tl, vertices.xy));\n"
    "    }\n"
    "    // If Top-right\n"
    "    else if (vertices.x > tr.x && vertices.y > tr.y)\n"
    "    {\n"
    "        alpha = 1.f - smoothstep(radiuses[1] - .0075f, radiuses[1], distance(tr, vertices.xy));\n"
    "    }\n"
    "    // If Bottom-right\n"
    "    else if (vertices.x > br.x && vertices.y < br.y)\n"
    "    {\n"
    "        alpha = 1.f - smoothstep(radiuses[2] - .0075f, radiuses[2], distance(br, vertices.xy));\n"
    "    }\n"
    "    // If Bottom-left\n"
    "    else if (vertices.x < bl.x && vertices.y < bl.y)\n"
    "    {\n"
    "        alpha = 1.f - smoothstep(radiuses[3] - .0075f, radiuses[3], distance(bl, vertices.xy));\n"
    "    }\n"
    "    // If straight edge\n"
    "    else\n"
    "    {\n"
    "        alpha = 1.f;\n"
    "    }\n"
    "}\n",

    [FILL_SOLID_COLOR_FS] =
    "// INFO ////////////////////////////////////////////////////////////////////////\n"
    "//                                                                            //\n"
    "//                                  pycasso                                   //\n"
    "//                                  =======                                   //\n"
    "//                                                                            //\n"
    "//    Cross-platform, hardware accelerated, constraint based GUI framework    //\n"
    "//                       Version: 0.5.02.035 (20140911)                       //\n"
    "//                                                                            //\n"
    "//                 File: shaders/fragment/fill_solid_color.fs                 //\n"
    "//                                                                            //\n"
    "//  For more information about the project, visit <http://www.pycasso.org>.   //\n"
    "//                       Copyright (C) 2014 Peter Varo                        //\n"
    "//                                                                            //\n"
    "//  This program is free software: you can redistribute it and/or modify it   //\n"
    "//   under the terms of the GNU General Public License as published by the    //\n"
    "//       Free Software Foundation, either version 3 of the License, or        //\n"
    "//                    (at your option) any later version.                     //\n"
    "//                                                                            //\n"
    "//    This program is distributed in the hope that it will be useful, but     //\n"
    "//         WITHOUT ANY WARRANTY; without even the implied warranty of         //\n"
    "//            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.            //\n"
    "//            See the GNU General Public License for more details.            //\n"
    "//                                                                            //\n"
    "//     You should have received a copy of the GNU General Public License      //\n"
    "//     along with this program, most likely a file in the root directory,     //\n"
    "//        called 'LICENSE'. If not, see <http://www.gnu.org/licenses>.        //\n"
    "//                                                                            //\n"
    "//////////////////////////////////////////////////////////////////////// INFO //\n"
    "\n"
    "// OpenGL Shading Language Version 1.50\n"
    "#version 150 core\n"
    "\n"
    "uniform vec4 color_base;\n"
    "\n"
    "void fill(in vec2 vertices, out vec4 color)\n"
    "{\n"
    "    color = color_base;\n"
    "}\n",

    [FILL_TEXTURE_FS] =
    "// INFO ////////////////////////////////////////////////////////////////////////\n"
    "//                                                                            //\n"
    "//                                  pycasso                                   //\n"
    "//                                  =======                                   //\n"
    "//                                                                            //\n"
    "//    Cross-platform, hardware accelerated, constraint based GUI framework    //\n"
    "//                       Version: 0.5.02.035 (20140911)                       //\n"
    "//                                                                            //\n"
    "//                   File: shaders/fragment/fill_texture.fs                   //\n"
    "//                                                                            //\n"
    "//  For more information about the project, visit <http://www.pycasso.org>.   //\n"
    "//                       Copyright (C) 2014 Peter Varo                        //\n"
    "//                                                                            //\n"
    "//  This program is free software: you can redistribute it and/or modify it   //\n"
    "//   under the terms of the GNU General Public License as published by the    //\n"
    "//       Free Software Foundation, either version 3 of the License, or        //\n"
    "//                    (at your option) any later version.                     //\n"
    "//                                                                            //\n"
    "//    This program is distributed in the hope that it will be useful, but     //\n"
    "//         WITHOUT ANY WARRANTY; without even the implied warranty of         //\n"
    "//            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.            //\n"
    "//            See the GNU General Public License for more details.            //\n"
    "//                                                                            //\n"
    "//     You should have received a copy of the GNU General Public License      //\n"
    "//     along with this program, most likely a file in the root directory,     //\n"
    "//        called 'LICENSE'. If not, see <http://www.gnu.org/licenses>.        //\n"
    "//                                                                            //\n"
    "//////////////////////////////////////////////////////////////////////// INFO //\n"
    "\n"
    "// OpenGL Shading Language Version 1.50\n"
    "#version 150 core\n"
    "\n"
    "uniform sampler2D texture_sampler;\n"
    "\n"
    "in vec2 textures;\n"
    "\n"
    "void fill(in vec2 vertices, out vec4 color)\n"
    "{\n"
    "    color = texture(texture_sampler, textures);\n"
    "}\n",

    [FILL_LINEAR_GRADIENT_FS] =
    "// INFO ////////////////////////////////////////////////////////////////////////\n"
    "//                                                                            //\n"
    "//                                  pycasso                                   //\n"
    "//                                  =======                                   //\n"
    "//                                                                            //\n"
    "//    Cross-platform, hardware accelerated, constraint based GUI framework    //\n"
    "//                       Version: 0.5.02.035 (20140911)                       //\n"
    "//                                                                            //\n"
    "//               File: shaders/fragment/fill_linear_gradient.fs               //\n"
    "//                                                                            //\n"
    "//  For more information about the project, visit <http://www.pycasso.org>.   //\n"
    "//                       Copyright (C) 2014 Peter Varo                        //\n"
    "//                                                                            //\n"
    "//  This program is free software: you can redistribute it and/or modify it   //\n"
    "//   under the terms of the GNU General Public License as published by the    //\n"
    "//       Free Software Foundation, either version 3 of the License, or        //\n"
    "//                    (at your option) any later version.                     //\n"
    "//                                                                            //\n"
    "//    This program is distributed in the hope that it will be useful, but     //\n"
    "//         WITHOUT ANY WARRANTY; without even the implied warranty of         //\n"
    "//            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.            //\n"
    "//            See the GNU General Public License for more details.            //\n"
    "//                                                                            //\n"
    "//     You should have received a copy of the GNU General Public License      //\n"
    "//     along with this program, most likely a file in the root directory,     //\n"
    "//        called 'LICENSE'. If not, see <http://www.gnu.org/licenses>.        //\n"
    "//                                                                            //\n"
    "//////////////////////////////////////////////////////////////////////// INFO //\n"
    "\n"
    "// OpenGL Shading Language Version 1.50\n"
    "#version 150 core\n"
    "\n"
    "// TODO: make variable count of stops and colors\n"
    "//       http://stackoverflow.com/questions/8099979/glsl-c-arrays-of-uniforms\n"
    "\n"
    "uniform mat2  color_rotation;\n"
    "uniform vec4  color_base;\n"
    "uniform vec4  color_stop;\n"
    "uniform float color_base_location;\n"
    "uniform float color_stop_location;\n"
    "\n"
    "void fill(in vec2 vertices, out vec4 color)\n"
    "{\n"
    "    // Linear gradient parameter\n"
    "    float t = ((color_rotation*vertices).y - color_base_location) /\n"
    "              (color_stop_location - color_base_location);\n"
    "\n"
    "    // Calculate gradient color value\n"
    "    color = mix(color_base, color_stop, t);\n"
    "}\n",

    [FILL_RADIAL_GRADIENT_FS] =
    "// INFO ////////////////////////////////////////////////////////////////////////\n"
    "//                                                                            //\n"
    "//                                  pycasso                                   //\n"
    "//                                  =======                                   //\n"
    "//                                                                            //\n"
    "//    Cross-platform, hardware accelerated, constraint based GUI framework    //\n"
    "//                       Version: 0.5.02.035 (20140911)                       //\n"
    "//                                                                            //\n"
    "//               File: shaders/fragment/fill_radial_gradient.fs               //\n"
    "//                                                                            //\n"
    "//  For more information about the project, visit <http://www.pycasso.org>.   //\n"
    "//                       Copyright (C) 2014 Peter Varo                        //\n"
    "//                                                                            //\n"
    "//  This program is free software: you can redistribute it and/or modify it   //\n"
    "//   under the terms of the GNU General Public License as published by the    //\n"
    "//       Free Software Foundation, either version 3 of the License, or        //\n"
    "//                    (at your option) any later version.                     //\n"
    "//                                                                            //\n"
    "//    This program is distributed in the hope that it will be useful, but     //\n"
    "//         WITHOUT ANY WARRANTY; without even the implied warranty of         //\n"
    "//            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.            //\n"
    "//            See the GNU General Public License for more details.            //\n"
    "//                                                                            //\n"
    "//     You should have received a copy of the GNU General Public License      //\n"
    "//     along with this program, most likely a file in the root directory,     //\n"
    "//        called 'LICENSE'. If not, see <http://www.gnu.org/licenses>.        //\n"
    "//                                                                            //\n"
    "//////////////////////////////////////////////////////////////////////// INFO //\n"
    "\n"
    "// OpenGL Shading Language Version 1.50\n"
    "#version 150 core\n"
    "\n"
    "uniform vec2  color_position;\n"
    "uniform vec4  color_base;\n"
    "uniform vec4  color_stop;\n"
    "uniform float color_base_location;\n"
    "uniform float color_stop_location;\n"
    "\n"
    "void fill(in vec2 vertices, out vec4 color)\n"
    "{\n"
    "    float t = distance(vertices, color_position);\n"
    "    color = mix(color_base, color_stop, t);\n"
    "}\n",

    [FILL_CONICAL_GRADIENT_FS] =
    "// INFO ////////////////////////////////////////////////////////////////////////\n"
    "//                                                                            //\n"
    "//                                  pycasso                                   //\n"
    "//                                  =======                                   //\n"
    "//                                                                            //\n"
    "//    Cross-platform, hardware accelerated, constraint based GUI framework    //\n"
    "//                       Version: 0.5.02.035 (20140911)                       //\n"
    "//                                                                            //\n"
    "//              File: shaders/fragment/fill_conical_gradient.fs               //\n"
    "//                                                                            //\n"
    "//  For more information about the project, visit <http://www.pycasso.org>.   //\n"
    "//                       Copyright (C) 2014 Peter Varo                        //\n"
    "//                                                                            //\n"
    "//  This program is free software: you can redistribute it and/or modify it   //\n"
    "//   under the terms of the GNU General Public License as published by the    //\n"
    "//       Free Software Foundation, either version 3 of the License, or        //\n"
    "//                    (at your option) any later version.                     //\n"
    "//                                                                            //\n"
    "//    This program is distributed in the hope that it will be useful, but     //\n"
    "//         WITHOUT ANY WARRANTY; without even the implied warranty of         //\n"
    "//            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.            //\n"
    "//            See the GNU General Public License for more details.            //\n"
    "//                                                                            //\n"
    "//     You should have received a copy of the GNU General Public License      //\n"
    "//     along with this program, most likely a file in the root directory,     //\n"
    "//        called 'LICENSE'. If not, see <http://www.gnu.org/licenses>.        //\n"
    "//                                                                            //\n"
    "//////////////////////////////////////////////////////////////////////// INFO //\n"
    "\n"
    "// OpenGL Shading Language Version 1.50\n"
    "#version 150 core\n"
    "\n"
    "out vec4 frag_color;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    frag_color = vec4(0.f, 0.f, 0.f, 1.f);\n"
    "}\n"
};

#endif /* _PYCASSO_RESOURCES_SHADERS_26875033728857023_ */
